version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: chatbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: chatbot_db
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatbot-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: chatbot-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chatbot.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - chatbot-network

volumes:
  postgres_data:


networks:
  chatbot-network:
    driver: bridge
